apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  labels:
    app: faces
  name: faces-gateway
  namespace: faces-frontend
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - faces.phight.club
      port:
        name: http
        number: 80
        protocol: HTTP
